from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_category_window(object):
    def setupUi(self, category_window):
        category_window.setObjectName("category_window")
        category_window.resize(1000, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/Logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        category_window.setWindowIcon(icon)
        category_window.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(category_window)
        self.centralwidget.setObjectName("centralwidget")
        self.category_category1_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category1_label.setGeometry(QtCore.QRect(30, 220, 200, 200))
        self.category_category1_label.setText("")
        self.category_category1_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/catergory1-electronics.jpg"))
        self.category_category1_label.setScaledContents(True)
        self.category_category1_label.setObjectName("category_category1_label")
        self.category_category2_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category2_label.setGeometry(QtCore.QRect(270, 220, 200, 200))
        self.category_category2_label.setText("")
        self.category_category2_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/Clothes.jpg"))
        self.category_category2_label.setScaledContents(True)
        self.category_category2_label.setObjectName("category_category2_label")
        self.category_category3_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category3_label.setGeometry(QtCore.QRect(510, 220, 200, 200))
        self.category_category3_label.setText("")
        self.category_category3_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/books.jpg"))
        self.category_category3_label.setScaledContents(True)
        self.category_category3_label.setObjectName("category_category3_label")
        self.category_category4_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category4_label.setGeometry(QtCore.QRect(750, 220, 200, 200))
        self.category_category4_label.setText("")
        self.category_category4_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/gaming.jpg"))
        self.category_category4_label.setScaledContents(True)
        self.category_category4_label.setObjectName("category_category4_label")
        self.category_category7_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category7_label.setGeometry(QtCore.QRect(510, 470, 200, 200))
        self.category_category7_label.setText("")
        self.category_category7_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/home and garden.jpg"))
        self.category_category7_label.setScaledContents(True)
        self.category_category7_label.setObjectName("category_category7_label")
        self.category_category6_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category6_label.setGeometry(QtCore.QRect(270, 470, 200, 200))
        self.category_category6_label.setText("")
        self.category_category6_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/sale.jpg"))
        self.category_category6_label.setScaledContents(True)
        self.category_category6_label.setObjectName("category_category6_label")
        self.category_category8_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category8_label.setGeometry(QtCore.QRect(750, 470, 200, 200))
        self.category_category8_label.setText("")
        self.category_category8_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/Sports supplies.jpg"))
        self.category_category8_label.setScaledContents(True)
        self.category_category8_label.setObjectName("category_category8_label")
        self.category_category5_label = QtWidgets.QLabel(self.centralwidget)
        self.category_category5_label.setGeometry(QtCore.QRect(30, 470, 200, 200))
        self.category_category5_label.setText("")
        self.category_category5_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/toys.jpg"))
        self.category_category5_label.setScaledContents(True)
        self.category_category5_label.setObjectName("category_category5_label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 1111, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.category_b3b3Logo_label = QtWidgets.QLabel(self.frame)
        self.category_b3b3Logo_label.setGeometry(QtCore.QRect(30, 10, 80, 80))
        self.category_b3b3Logo_label.setStyleSheet("background-color: transparent;")
        self.category_b3b3Logo_label.setText("")
        self.category_b3b3Logo_label.setPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/Logo.jpg"))
        self.category_b3b3Logo_label.setScaledContents(True)
        self.category_b3b3Logo_label.setObjectName("category_b3b3Logo_label")
        self.category_background_label = QtWidgets.QLabel(self.frame)
        self.category_background_label.setGeometry(QtCore.QRect(0, 0, 1121, 90))
        self.category_background_label.setStyleSheet("background-color:rgb(6, 160, 170);")
        self.category_background_label.setText("")
        self.category_background_label.setObjectName("category_background_label")
        self.category_cart_pushButton = QtWidgets.QPushButton(self.frame)
        self.category_cart_pushButton.setGeometry(QtCore.QRect(900, 30, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.category_cart_pushButton.setFont(font)
        self.category_cart_pushButton.setStyleSheet("border: 5px solid white;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(5, 159, 169);\n"
"border-radius:10px;\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/pyqt5/MATELRIAL/IMG/icons8-cart-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.category_cart_pushButton.setIcon(icon4)
        self.category_cart_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.category_cart_pushButton.setObjectName("category_cart_pushButton")
        self.category_background_label.raise_()     
        self.category_b3b3Logo_label.raise_()
        self.category_cart_pushButton.raise_()
        category_window.setCentralWidget(self.centralwidget)
        self.retranslateUi(category_window)
        QtCore.QMetaObject.connectSlotsByName(category_window)
    def retranslateUi(self, category_window):
        _translate = QtCore.QCoreApplication.translate
        category_window.setWindowTitle(_translate("category_window", "B3B3 - Category"))
        self.category_cart_pushButton.setText(_translate("category_window", "Cart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    category_window = QtWidgets.QMainWindow()
    ui = Ui_category_window()
    ui.setupUi(category_window)
    category_window.show()
    sys.exit(app.exec_())
